### ISSUE TITLE
cant run 

### ISSUE THREAD

**Issue by jjcampis** [nunogois/quasar-ble#2]
Hello i've downloaded and try tu run but it throws a lot of errors tested in 2 machines by now running windows...

`
 • Compiling:
 └── SPA █████████            40% building 1/3 modules 2 active

C:\Users\JJ\Documents\develop\quasar-ble-master\node_modules\loader-runner\lib\LoaderRunner.js:133
                if(isError) throw e;
                            ^

[  Error: error:0308010C:digital envelope routines::unsupported

  - hash:71 new Hash
    node:internal/crypto/hash:71:19

  - node:crypto:133 Object.createHash
    node:crypto:133:10

  - createHash.js:135 module.exports
    [quasar-ble-master]/[webpack]/lib/util/createHash.js:135:53

  - NormalModule.js:417 NormalModule._initBuildHash
    [quasar-ble-master]/[webpack]/lib/NormalModule.js:417:16

  - NormalModule.js:471 handleParseError
    [quasar-ble-master]/[webpack]/lib/NormalModule.js:471:10

  - NormalModule.js:503 
    [quasar-ble-master]/[webpack]/lib/NormalModule.js:503:5

  - NormalModule.js:358 
    [quasar-ble-master]/[webpack]/lib/NormalModule.js:358:12

  - LoaderRunner.js:373 
    [quasar-ble-master]/[loader-runner]/lib/LoaderRunner.js:373:3

  - LoaderRunner.js:214 iterateNormalLoaders
    [quasar-ble-master]/[loader-runner]/lib/LoaderRunner.js:214:10

  - LoaderRunner.js:221 iterateNormalLoaders
    [quasar-ble-master]/[loader-runner]/lib/LoaderRunner.js:221:10

] {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0`

**Comment by jjcampis** [comment]
ahora tengo este error, ejecute npm update y luego baje de version a node 16.13.0 con nvm...

`] {
  errors: [
    {
      keyword: 'type',
      dataPath: '.eslint',
      schemaPath: '#/definitions/EsLintReporterOptions/type',
      params: { type: 'object' },
      message: 'should be object',
      schema: 'object',
      parentSchema: {
        type: 'object',
        properties: {
          files: {
            oneOf: [Array],
            description: 'List of glob patterns or files to be linted.'
          },
          enabled: { type: 'boolean', description: 'Enable EsLint reporter.' },
          memoryLimit: {
            type: 'number',
            description: 'Memory limit for EsLint reporter process.'
          },
          options: {
            type: 'object',
            description: 'Custom options to be passed to the EsLint engine.',
            additionalProperties: true
          }
        },
        required: [ 'files' ]
      },
      data: true
    }
  ],
  schema: {
    '$schema': 'http://json-schema.org/draft-07/schema#',
    type: 'object',
    properties: {
      async: {
        type: 'boolean',
        description: 'When true, plugin will not block compilation to finish issues checking'
      },
      typescript: { '$ref': '#/definitions/TypeScriptReporterOptions' },
      eslint: { '$ref': '#/definitions/EsLintReporterOptions' },
      formatter: { '$ref': '#/definitions/FormatterOptions' },
      issue: { '$ref': '#/definitions/IssueOptions' },
      logger: { '$ref': '#/definitions/LoggerOptions' }
    },
    additionalProperties: false,
    definitions: {
      Formatter: { instanceof: 'Function' },
      ComplexFormatterPreferences: {
        type: 'object',
        properties: {
          type: { '$ref': '#/definitions/FormatterType' },
          options: { type: 'object', additionalProperties: true }
        },
        required: [ 'type' ]
      },
      FormatterType: { type: 'string', enum: [ 'basic', 'codeframe' ] },
      IssueMatch: {
        type: 'object',
        properties: {
          origin: { type: 'string', enum: [Array] },
          severity: { type: 'string', enum: [Array] },
          code: { type: 'string' },
          file: { type: 'string' }
        }
      },
      IssuePredicate: { instanceof: 'Function' },
      IssuePredicateOption: {
        oneOf: [
          { '$ref': '#/definitions/IssuePredicate' },
          { '$ref': '#/definitions/IssueMatch' },
          { type: 'array', items: [Object] }
        ]
      },
      LoggerType: {
        type: 'string',
        enum: [ 'console', 'webpack-infrastructure', 'silent' ]
      },
      Logger: {
        type: 'object',
        properties: {
          error: { instanceof: 'Function' },
          info: { instanceof: 'Function' },
          log: { instanceof: 'Function' }
        }
      },
      TypeScriptReporterOptions: {
        oneOf: [
          {
            type: 'boolean',
            description: 'Enable TypeScript reporter.'
          },
          { type: 'object', properties: [Object] }
        ]
      },
      TypeScriptVueExtensionOptions: {
        oneOf: [
          {
            type: 'boolean',
            description: 'Enable TypeScript Vue extension.'
          },
          { type: 'object', properties: [Object] }
        ]
      },
      EsLintReporterOptions: {
        type: 'object',
        properties: {
          files: {
            oneOf: [Array],
            description: 'List of glob patterns or files to be linted.'
          },
          enabled: { type: 'boolean', description: 'Enable EsLint reporter.' },
          memoryLimit: {
            type: 'number',
            description: 'Memory limit for EsLint reporter process.'
          },
          options: {
            type: 'object',
            description: 'Custom options to be passed to the EsLint engine.',
            additionalProperties: true
          }
        },
        required: [ 'files' ]
      },
      FormatterOptions: {
        oneOf: [
          { '$ref': '#/definitions/FormatterType' },
          { '$ref': '#/definitions/ComplexFormatterPreferences' },
          { '$ref': '#/definitions/Formatter' }
        ]
      },
      IssueOptions: {
        type: 'object',
        properties: {
          include: { '$ref': '#/definitions/IssuePredicateOption' },
          exclude: { '$ref': '#/definitions/IssuePredicateOption' }
        }
      },
      LoggerOptions: {
        type: 'object',
        properties: {
          infrastructure: { oneOf: [Array] },
          issues: { oneOf: [Array] },
          devServer: {
            type: 'boolean',
            description: 'Enable reporting to Webpack Dev Server.'
          }
        }
      }
    }
  },
  headerName: 'ForkTsCheckerWebpackPlugin',
  baseDataPath: 'configuration',
  postFormatter: null,
  message: 'Invalid configuration object. ForkTsCheckerWebpackPlugin has been initialized using a configuration object that does not match the API schema.\n' +
    ' - configuration.eslint should be an object:\n' +
    '   object { files, enabled?, memoryLimit?, options?, … }'`

**Comment by nunogois** [comment]
Hi @jjcampis,

I'd like to remind you that this repository hasn't been updated since [**June 2021**](https://github.com/nunogois/quasar-ble/commits/master). This means it's not currently being actively maintained.

However, I'm open and appreciative of any contributions you might have. Given the popularity of this repository, I might consider updating it in the future, but I can't promise this.

I also [encourage](https://opensource.stackexchange.com/questions/6134/should-i-require-that-new-issues-be-written-in-english) contributors to use English for their comments for broader accessibility.

That being said, I was able to get the project up and running by following these steps:

1. `git clone https://github.com/nunogois/quasar-ble.git`
2. `nvm use 16`
3. `yarn`
4. `cd src-capacitor && yarn`
5. `cd .. && yarn dev`

I hope this helps. Additionally, if you're considering recreating this project with the latest versions, it would be fantastic if you could submit a pull request with these updates. This would greatly assist others who come across this project, like you did.

Looking forward to seeing your contributions!
